spring.application.name=customer
server.port=8090

spring.mongodb.uri=mongodb://oumaima:oumaima@localhost:27017/customer?authSource=admin
logging.level.org.springframework.boot.context.config=DEBUG
logging.level.org.springframework.data.mongodb=DEBUG
logging.level.org.mongodb.driver=DEBUG