spring.mongodb.username=oumaima
spring.mongodb.password=oumaima
spring.mongodb.host=localhost
spring.mongodb.port=27017
spring.mongodb.database=notification
spring.mongodb.authentication-database=admin

spring.kafka.consumer.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=paymentGroup,orderGroup
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.properties.spring.json.type.mapping=orderConfirmation:com.oumaima.notification.kafka.order.OrderConfirmation,paymentNotificationRequest:com.oumaima.notification.kafka.payment.PaymentConfirmation

spring.mail.host=localhost
spring.mail.port=1025
spring.mail.username=oumaima
spring.mail.password=oumaima

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.trust=*

spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=3000
spring.mail.properties.mail.smtp.writetimeout=5000
server.port=8040