server.port=8070
spring.datasource.url=jdbc:postgresql://localhost:5433/order
spring.datasource.username=oumaima
spring.datasource.password=oumaima
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=create
#check just schema
spring.jpa.database=postgresql
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.kafka.producer.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.type.mapping=orderConfirmation:com.oumaima.order.kafka.OrderConfirmation
#8222 of gateway
application.config.customer-url=http://localhost:8222/api/v1/customers
application.config.product-url=http://localhost:8222/api/v1/products
application.config.payment-url=http://localhost:8222/api/v1/payments

